### ISSUE TITLE
Add a way to go directly to the categories of the project (Issues, Merge Request,...)

### ISSUE THREAD

**Issue by dewey** [lukewaite/alfred-gitlab#11]
Thanks for the plugin! It's a great time saver, what would also be cool is that if you type `gl yourproject` and then you can select branches, merge-request, issue and it opens the corresponding pages of the project.

**Comment by tclass** [comment]
I added a "Filter List" so you can go to Overview, Merge Request, Issues or Pipelines. It's a manual list so nothing from the API. You can easily add other commands in the workflow view

**Comment by lukewaite** [comment]
Released in [v1.5.0](https://github.com/lukewaite/alfred-gitlab/releases/tag/v1.5.0) thanks to @tclass
