### ISSUE TITLE
How to force workflow to update cache

### ISSUE THREAD

**Issue by addozhang** [lukewaite/alfred-gitlab#6]
Using api can retrieve projects which I want, but with workflow not.

How to force it to update local cache if local cache really exists?

**Comment by wd** [comment]
You can delete it by hand, the cache file is locate at `~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.lukewaite.alfred-gitlab/projects.cpickle`.

**Comment by lukewaite** [comment]
You can run `gl workflow:delcache` to clear the cache via alfred.
